apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-console
spec:
  template:
    metadata:
      labels:
        run: es-console
    spec:
      {{ if .Values.podUID }}
      securityContext:
        runAsUser: {{ .Values.podUID }}
      {{ end }}

      imagePullSecrets:
      - name: commercial-credentials

      containers:
      - name: dnsmasq
        image: {{ .Values.goDnsmasqImage }}:{{ .Values.goDnsmasqVersion }}
        resources:
          requests:
            cpu: {{ default .Values.defaultCPURequest .Values.esConsoleDnsmasqCPURequest }}
            memory: {{ default .Values.defaultMemoryRequest .Values.esConsoleDnsmasqMemoryRequest }}
          limits:
            cpu: {{ default .Values.defaultCPULimit .Values.esConsoleDnsmasqCPULimit }}
            memory: {{ default .Values.defaultMemoryLimit .Values.esConsoleDnsmasqMemoryLimit }}
        args:
          - --listen
          - "127.0.0.1:5353"
          - --verbose
          - --enable-search
      - name: es-console
        image: {{ tpl .Values.esConsoleImage . }}:{{ .Values.esConsoleVersion }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
          requests:
            cpu: {{ default .Values.defaultCPURequest .Values.esConsoleCPURequest }}
            memory: {{ default .Values.defaultMemoryRequest .Values.esConsoleMemoryRequest }}
          limits:
            cpu: {{ default .Values.defaultCPULimit .Values.esConsoleCPULimit }}
            memory: {{ default .Values.defaultMemoryLimit .Values.esConsoleMemoryLimit }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d

      volumes:
      - name: config-volume
        configMap:
          name: es-console
